version: '3.8'
name: ${NAME}

services:
  animal-shelter-backend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - ORIGINS=${ORIGINS}
    container_name: animal-shelter-backend-${NAME}
    networks:
      - animal-shelter

networks:
  animal-shelter:
    name: ${NETWORK}
    external: true