name: Server Deploy

on:
  push:
    branches: [dev]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      NAME: dev
      NETWORK: animal-shelter-dev
      ORIGINS: https://dev.pawparadise24.de
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Images
        run: docker compose up -d --build